//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace logistic
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class logisticEntities2 : DbContext
    {
        private static logisticEntities2 _context;
        public logisticEntities2()
            : base("name=logisticEntities")
        {
        }
        public static logisticEntities2 GetContext()
        {
            if (_context == null)
                _context = new logisticEntities2();
            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<clients> clients { get; set; }
        public virtual DbSet<drivers> drivers { get; set; }
        public virtual DbSet<orders> orders { get; set; }
        public virtual DbSet<status_orders> status_orders { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<transport> transport { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
